kind: Deployment
apiVersion: apps/v1
metadata:
  name: parking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-api
  template:
    metadata:
      labels:
        app: parking-api
    spec:
      containers:
        - name: parking-api-container # Assigns the name
          image: parking-api:1.0 # Specifies image, can be refering to online repo like dockerhub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000 # Specifies which port the container will listen on
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification # Assigns the name
          image: notification-service:1.0 # Specifies image, can be refering to online repo like dockerhub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000 # Specifies which port the container will listen on
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: eventstore-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstore-service
  template:
    metadata:
      labels:
        app: eventstore-service
    spec:
      containers:
        - name: eventstore # Assigns the name
          image: eventstore-service:1.5 # Specifies image, can be refering to online repo like dockerhub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000 # Specifies which port the container will listen on
---

apiVersion: v1
kind: Service
metadata:
  name: parking-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: parking-api
      port: 5000
      targetPort: 8080
  selector:
    app: parking-api
---

apiVersion: v1
kind: Service
metadata:
  name: eventstore-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: eventstore-api
      port: 5100
      targetPort: 8080
  selector:
    app: eventstore-service