services:


  parking:
    image: ${DOCKER_REGISTRY-}parking
    build:
      context: .
      dockerfile: Parking/Dockerfile
    ports:
       - "9100:9100"

  Notification:
    image: ${DOCKER_REGISTRY-}notification
    build:
      context: .
      dockerfile: Notification/Dockerfile
    ports:
       - "9200:9200"


  EventStore:
    image: ${DOCKER_REGISTRY-}eventstore
    build:
      context: .
      dockerfile: EventStore/Dockerfile
    ports:
       - "9300:9300"


  Pizzaria:
    image: ${DOCKER_REGISTRY-}pizzaria
    build:
      context: .
      dockerfile: Pizzaria/Dockerfile
    ports:
       - "9400:9400"
